from tkinter import *
fenetre = Tk()
bouton=Button(fenetre, text="Fermer", command=fenetre.quit)
bouton.pack()
label = Label(fenetre, text="Je me nomme le plus Grand Corps malade", bg="#518696")
label.pack()
value = StringVar()
value.set("agl upb")
entree = Entry(fenetre, textvariable=str, width=30)
entree.pack()
value = StringVar()
bouton1 = Radiobutton(fenetre, text="Oui", variable=value, value=1)
bouton2 = Radiobutton(fenetre, text="Non", variable=value, value=2)
bouton3 = Radiobutton(fenetre, text="Je ne sais pas", variable=value, value=3)
bouton1.pack()
bouton2.pack()
bouton3.pack()
label = Label(fenetre, text="Bienvenue au cours de AGL")
label.pack()

fenetre.mainloop()